version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: airline_frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    environment:
      - VITE_API_BASE=http://app:3000
    depends_on:
      - app
