version: "3.9"

services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: airline_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: ./backend
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=airline_db
      - ORM=${ORM:-prisma}   # default Prisma, can override with ORM=sequelize
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    environment:
      - VITE_API_BASE=http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  db_data:
